### ISSUE TITLE
In Endpoint data model, there is a field of "Bypass Decapsulation", in which scenarios it will be used? 

### ISSUE THREAD

**Issue by yongming** [futurewei-cloud/mizar#10]

**Comment by zasherif** [comment]
We need to support cases in which endpoint access the same packets Mizar sends on the substrate network. These shall be privileged endpoints that implement actual network functions and require access to the packet metadata (in the outer header). The functionality is also needed for inter-operability with existing networking solutions.

**Comment by yongming** [comment]
Okay, actually I am thinking it may be used in the overlay mode container networking, esp. multi-tenancy in K8S, two layers of networking(VPC: for IaaS tenant and overlayer on VPC: K8S tenant) can be merged into one layer with Geneve encap, endpoints for container can access some outside header field to get K8S layer tenant ID.

**Comment by zasherif** [comment]
@yongming Thank you for your interest in Mizar. I will close this issue for now. For further questions, please consider joining the project [Slack Channel](https://join.slack.com/t/mizar-group/shared_invite/enQtNzUzOTYxOTM0ODY2LTE2OWYyN2Q2MjU3ZDFmNGUwZDlmYzNmNzk3MDRjNDMwMDQwMmQ3MDNlOWE3MzIzODAyYjQwZWMwYzY2ZmQzNmU)
