### ISSUE TITLE
Application Acceleration in use cases of service mesh 

### ISSUE THREAD

**Issue by denghuihuang** [futurewei-cloud/mizar#12]
Nowadays, service mesh is attractive to some customers.  Public cloud vendors, such as, Google, Huawei, already provides service mesh service to customer.  Service mesh architecture mostly applied  sidecar model, like envoy in lstio project. As we know, in sidercar model, dataplane component such as envoy, is facing performance problem which is packet going through tcp stack tiwce, even two applications communicate each other in the same host. when mizar as a container network solution, how to do application acceleration?

**Comment by XiaoningDing** [comment]
I don't think current Mizar implementation will help accelerate in this use case.  Take envoy as an example, traffic first needs to go through the sender's TCP-IP stack where the interception logic is injected.  This happens before Mizar kicks in -- Mizar endpoint agent is running in XDP layer, as BPF programs attached to devices.  Even Mizar efficiently redirects packets from one veth endpoint to another, the packet still needs to goes through the receiver’s stack.  

Mizar is designed for generic large-scale cloud networking, and hasn’t started particular optimization for container scenarios. Recently we just started working on this part. The issue you raised is a good use case in the scenario. There could be some solutions like attaching BPF to earlier hooks, other interception mechanisms, or some AF_XDP based solutions. But this require further evaluation and design. If you have any proposals feel free to create a feature-request issue, and we can work together on it.

**Comment by zasherif** [comment]
I will close this issue for now. For further questions, please consider joining the project [Slack Channel](https://join.slack.com/t/mizar-group/shared_invite/enQtNzUzOTYxOTM0ODY2LTE2OWYyN2Q2MjU3ZDFmNGUwZDlmYzNmNzk3MDRjNDMwMDQwMmQ3MDNlOWE3MzIzODAyYjQwZWMwYzY2ZmQzNmU)
