### ISSUE TITLE
Endpoint failed to start

### ISSUE THREAD

**Issue by clu2xlu** [futurewei-cloud/mizar#120]
After running $ sudo ./kind_setup.sh
and then $ kubectl create -f nginx.yaml
The nginx endpoint stuck in CreatingContainer state for a long time

When run 
kubectl describe pods: 
[Error Message]  Warning  FailedCreatePodSandBox  104s               kubelet, kind-worker4  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "0f31caad287b942bf475f653660c1d8078c64f3bc65a4efc78d5dfba3cac2053": netplugin failed with no error message

Please double check if the net and vpc got created successfully: 
kubectl get vpcs
kubectl get nets

Sometimes, you get this error if there is no vpc and net created
kind-setup.sh sets up vpc0 and net0 when first time running the script. 
After the first attempt, it sometimes fail to create vpc and net, thus cause this error

**Comment by zasherif** [comment]
Can you share your pod yaml file

**Comment by clu2xlu** [comment]
it's an issue with my dev machine environment setup
