### ISSUE TITLE
 If net0 and vpc0 (the default kube cluster's network and vpc) were not present, create pod would fail

### ISSUE THREAD

**Issue by clu2xlu** [futurewei-cloud/mizar#122]
[bug] kind-setup does not create vpcs and nets which cause kubectl create to fail. 
 However, in our test, we first create vpc and then net. 
 Create pod should succeed since vpc(myvpc6) and net(mynet6) were created previously. 
But create pod failed despite of the fact that myvpc6 and mynet6 are present. 
 Why create pod still fail (with the same error message) as if there is no network or vpc

**Comment by zasherif** [comment]
I think this related to https://github.com/futurewei-cloud/mizar/issues/121

**Comment by clu2xlu** [comment]
https://github.com/futurewei-cloud/mizar/blob/dev-next/mgmt/daemon/cni_service.py#L145-L149
when creating a new endpoint, it always pick the default vpc and net

**Comment by zasherif** [comment]
Correct. We don't have a mechanism right now to pass the VPC and Net info in the pod creation. It is only in the simple endpoint creation. We have two quick possibilities:

1. Annotate the pod with a vpc and net, and we need to have the built-in operators modified to create the endpoints based on these...
2. We don't use any built-in objects for the multi-vpc/multi-net tests and only create simple endpoints directly.

**Comment by clu2xlu** [comment]
resolved
