### ISSUE TITLE
Question: how luigi will be used in operator? 

### ISSUE THREAD

**Issue by yongming** [futurewei-cloud/mizar#149]
Per my understanding, luigi is introduced to schedule object updating workflows. But so far I only find run_task in the code, no run_workflow. A little confused, is luigi really needed here?

**Comment by zasherif** [comment]
The method name are confusing, we initially started with run_task to run a single task with a local scheduler during development. We moved to a Luigi central scheduler and run_task actually runs a workflow: https://github.com/zasherif/mizar/commit/2da52cccc6742954607e82bce52494f7d8e18311

The run workflow method is pretty much the same but uses the local scheduler: https://github.com/futurewei-cloud/mizar/blob/dev-next/mgmt/common/common.py#L177

We will change the function names to remove the confusion.

**Comment by yongming** [comment]
I checked all the implemented WorkflowTask class for mizar objects, found all the` requires `return empty array like below:
```
	def requires(self):
		logger.info("Requires {task}".format(task=self.__class__.__name__))
		return []

```
Seems there is no dependency in those tasks, all are "single task workflow" so far?

**Comment by zasherif** [comment]
That is right. At the moment we don't see a need to complicate the workflows into multiple tasks that need to be scheduled independently. That is said, there is optimizations that shall be done here like for example having parallel tasks that program the bouncers in parallel.

**Comment by yongming** [comment]
Thanks for the your comments, get it.
