### ISSUE TITLE
what if container is located in vm not in hypervisor layer

### ISSUE THREAD

**Issue by denghuihuang** [futurewei-cloud/mizar#7]
In case of public cloud scenarios, most public cloud providers provide container orchestrator services, such as, CCE service of huaweicloud, EKS service of aws,  both of them deploy container in those virtual machine, not in hypervisor layer. I check out this doc of Mizar, currently Mizar consider container is located in hypervisor layer, Does Mizar have plan to support container is deployed in virtual machine?

**Comment by XiaoningDing** [comment]
Mizar supports the scenario you mentioned. There are two different networking modes for containers in VMs, and Mizar supports both.

In the first mode, containers inside a VM consume the underlying IaaS VPC IP directly.  Examples of such solutions are AWS EKS (https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/cni-proposal.md) and Ali Terway (https://github.com/AliyunContainerService/terway).  Basically, a VPC vNIC is attached to a VM, and then either it is moved to container's namespace directly, or traffic is routed to the container inside the VM.  With this mode Mizar is deployed in IaaS layer to provide VPC infrastructure. And it's pretty much transparent to Mizar.  Services like CCE need to have their own plugin to allocate and move vNICs, just like Terway and EKS does.

In the second mode, containers in a VM are not consuming VPC IP directly. Instead they build another layer of overlay networking inside the VM cluster.  In this mode Mizar needs to be deployed inside the VM cluster, just like today how we deploy flannel or Calico.

By the way, Mizar isn’t coupled with hypervisors.  Mizar exposes a network endpoint as a virtual network interface on computing hosts, such as one end of a VETH pair or a tap device.  This network interface can be connected to any computing entity.

**Comment by denghuihuang** [comment]
In the first mode, AWS EKS has some limitations, such as,  ENI limitations, limitation of secondary IP address of one ENI? How to break this kind of limitaion?

**Comment by XiaoningDing** [comment]
Some sample solutions that EKS has been working on to lift the limit: https://github.com/aws/containers-roadmap/issues/398 https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-eni.html

Come to Mizar itself, we should be able to support high-density endpoints on one host. So far one endpoint is represented by a veth pair from Mizar's point of view.  I tried creating thousands of veth paris on one host and they seem OK.  Also our endpoint provisioning process is relatively lightweight. Since we haven't implemented all features and haven't tested high-density scenario end-to-end, of course there could be other bottlenecks that we haven't identified yet.

**Comment by XiaoningDing** [comment]
I forgot to mention the hypervisor limit of virtual network devices, which might be the bottleneck. Although it's out of Mizar scope but it still hurts endpoint density. In this case Mizar probably can support the trunk endpoint as well.

**Comment by zasherif** [comment]
@denghuihuang Thank you for your interest in Mizar. I will close this issue for now. For further questions, please consider joining the project [Slack Channel](https://join.slack.com/t/mizar-group/shared_invite/enQtNzUzOTYxOTM0ODY2LTE2OWYyN2Q2MjU3ZDFmNGUwZDlmYzNmNzk3MDRjNDMwMDQwMmQ3MDNlOWE3MzIzODAyYjQwZWMwYzY2ZmQzNmU)
